name: Unit tests
on: [push]
jobs:
    Project-Unit-Tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - name: List files in the repository
              working-directory: ./public
              run: |
                  ls ${{ github.workspace }}
            - name: Install dependencies
              working-directory: ./public
              run: npm install
            - name: Cypress run
              working-directory: ./public
              uses: cypress-io/github-action@v4
              with:
                  build: npm run build
                  start: npm start
                  wait-on: "http://localhost:3000"
